# Generated by Django 5.1.4 on 2025-01-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'pending'), ('Готово', 'ready'), ('Оплачено', 'paid')], default='pending', max_length=20),
        ),
    ]
